-- Users --> Profile 1 to 1
-- Profile
-- Category --> Product 1 to Many
-- Product
-- Order
CREATE TABLE users(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	password TEXT NOT NULL,
	username VARCHAR(320) UNIQUE NOT NULL
);

CREATE TABLE profiles (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	bio TEXT,
	avatar TEXT,
	is_verified BOOLEAN DEFAULT False,
	user_id BIGINT UNIQUE NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

-- I WANNA XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX I NEED A XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

CREATE TABLE categories (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE products(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL, 
	price INTEGER NOT NULL,
	description TEXT,
	category_id BIGINT REFERENCES categories (id) ON DELETE RESTRICT
);

CREATE TABLE orders (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_products(
	product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
	order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
	quantity INTEGER NOT NULL
);

SELECT * FROM order_products;

DROP TABLE profiles;